import java.util.*;
import java_cup.runtime.*;

terminal BREAK, GTSIGN, DGTSIGN, PIPE, DPIPE, DAMP;
terminal String ARG, STRINGCONST;

non terminal Node               program;
non terminal ListNode           stmtlist;
non terminal Node               pipeline;
non terminal Node               comm, stmt;
non terminal List<String>       arglist;
non terminal List<RedirNode>    redirs;

precedence left BREAK;

start with program;

program ::= stmtlist:sl                         {: RESULT = sl; :}
    ;

stmtlist    ::= stmt:s                          {: RESULT = new ListNode(new ArrayList<>()); RESULT.nodes.add(s); :}
    | stmtlist:sl BREAK stmt:s                  {: sl.nodes.add(s); RESULT = sl; :}
    | stmtlist:sl BREAK                         {: RESULT = sl; :}
    ;
stmt        ::= pipeline:p                      {: RESULT = p; :}
    ;
pipeline    ::= comm:c                          {: RESULT = c; :}
    | pipeline:p PIPE comm:c                    {: RESULT = new PipeNode(p, c); :}
    | pipeline:p DPIPE comm:c                   {: RESULT = new ErrCondNode(2, p, c); :}
    | pipeline:p DAMP comm:c                    {: RESULT = new ErrCondNode(1, p, c); :}
    ;
comm        ::= arglist:al redirs:r             {: RESULT = new CommNode(al, r); :}
    ;
arglist     ::= ARG:a                           {: RESULT = new LinkedList<String>(); RESULT.add(a); :}
    | arglist:al ARG:argument                   {: al.add(argument); RESULT = al; :}
    ;
redirs ::=                                      {: RESULT = new ArrayList<RedirNode>(); :}
    | redirs:r GTSIGN ARG:a                     {: r.add(new RedirNode(1, a)); RESULT = r; :}
    | redirs:r DGTSIGN ARG:a                    {: r.add(new RedirNode(2, a)); RESULT = r; :}
    ;
